version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "Building complete"
  test-production:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "Testing complete"
  deploy:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "Deploy complete"

workflows:
  build-test-and-deploy:
    jobs:
      - build
      - test-production:
          requires:
            - build
      - deploy:
          requires:
            - test-production
          filters:
            branches:
              only: production