version: 2.1

parameters:
  condition-workflow:
    type: boolean
    default: true

jobs:
  my-job:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - when:
          condition:
             equal: [master, << pipeline.git.branch >>]
          steps:
            - run: echo "I am on master"

  conditional-job:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "This ran on a pipeline parameter"

workflows:
  my-workflow:
    jobs:
      - my-job

  conditional-workflow:
    when:
      and:
        - equal: [condition-workflow, true]
    jobs:
      - conditional-job