version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "Building complete"
  test-node:
    docker:
      - image: cimg/node:17.6.0
    steps:
      - run: echo "Testing complete"
  test-node-16:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - run: echo "Testing complete"
  test-node-14:
    docker:
      - image: cimg/node:14.19.0
    steps:
      - run: echo "Testing complete"
  deploy:
      docker:
        - image: cimg/base:2022.03
      steps:
        - run: echo "DEPLOYING" # Make sure all tests pass first!
      

workflows:
  build-test-and-deploy:
    jobs:
      - build
      - test-node:
          requires:
            - build
      - test-node-16:
          requires:
            - build
      - test-node-14:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test-node
            - test-node-14
            - test-node-16